import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/studio');await page.locator('[data-action="new"]').click();await page.locator('[name="name"]').fill('Laboratorio di prova');await page.locator('[name="width"]').fill('20');await page.locator('[name="depth"]').fill('10');await page.locator('#new-form button').click();
if(await page.locator('#area').textContent()!=='200 m²')throw Error('Area stanza errata');
await page.locator('[data-action="reference"]').click();await page.locator('#file').setInputFiles('test-results/editor.png');await page.locator('[data-field="ref.width"]').waitFor();await page.locator('[data-field="ref.width"]').fill('20');await page.locator('[data-field="ref.width"]').press('Tab');
await page.locator('.step[data-mode="layout"]').click();await page.locator('[data-action="image"]').click();await page.locator('#file').setInputFiles('test-results/editor.png');await page.locator('[data-text="name"]').waitFor();
await page.locator('[data-text="name"]').fill('Immagine importata');await page.locator('[data-text="name"]').press('Tab');
await page.locator('.top-actions [data-action="export"]').click();const promise=page.waitForEvent('download');await page.locator('[data-action="save-json"]').click();const download=await promise;await download.saveAs('test-results/imports.spazio.json');const data=JSON.parse(await fs.readFile('test-results/imports.spazio.json'));if(!data.reference.src.startsWith('data:image/png')||!data.objects[0].image)throw Error('Asset mancanti');
await page.locator('[data-action="close"]').click();await page.locator('.brand').click();await page.locator('[data-action="import"]').click();await page.locator('#file').setInputFiles('test-results/imports.spazio.json');await page.locator('#dialog').waitFor({state:'hidden'});if(await page.locator('#project-name').inputValue()!=='Laboratorio di prova')throw Error('Import incompleto');
await page.locator('.brand').click();await page.locator('[data-action="import"]').click();await page.locator('#file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":500}')});await page.locator('#toast.show').waitFor();if(await page.locator('#project-name').inputValue()!=='Laboratorio di prova')throw Error('Import invalido ha corrotto il progetto');
await page.locator('[data-action="close"]').click();await page.locator('.top-actions [data-action="export"]').click();for(const [action,ext] of [['save-svg','svg'],['save-csv','csv'],['report','html']]){const pr=page.waitForEvent('download');await page.locator(`[data-action="${action}"]`).click();const d=await pr;await d.saveAs('test-results/output.'+ext);}
await page.locator('[data-action="close"]').click();await page.locator('.brand').click();await page.locator('[data-action="demo"]').click();await page.locator('.top-actions [data-action="visit"]').click();await page.waitForTimeout(400);await page.screenshot({path:'test-results/visit-demo.png'});
await browser.close();if(errors.length)throw Error(errors.join('\n'));console.log('Nuovo spazio, riferimento, immagini, reimportazione, rifiuto file invalido, SVG/CSV/scheda: OK.');

