import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=process.env.SPAZIO_TEST_URL || 'http://127.0.0.1:4175';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[],failed=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('response',response=>{if(response.url().startsWith(base) && response.status()>=400)failed.push(`${response.status()} ${response.url()}`);});
try {
  await page.goto(base+'/');
  await page.getByRole('heading',{name:'Inizia da qui',exact:true}).waitFor();
  assert.equal(await page.locator('#inizia .start-card img').count(),3);
  await page.locator('[data-scene]').nth(1).click();
  assert.equal(await page.locator('[data-scene]').nth(1).getAttribute('aria-pressed'),'true');
  await page.screenshot({path:'test-results/release-home.png'});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:1500,height:1000});
  await page.goto(base+'/templates');
  await page.locator('h1').waitFor();
  await page.goto(base+'/studio?start=new');
  await page.locator('#new-form button[type=submit]').click();
  await page.locator('[data-mode=layout]').click();
  assert.ok(await page.locator('#plan-transform-tools').isVisible());
  const buttons=await page.locator('#plan-transform-tools button').all();
  const boxes=await Promise.all(buttons.map(button=>button.boundingBox()));
  assert.ok(boxes[1].y>boxes[0].y);
  await page.locator('#general-light').fill('0.6');
  await page.locator('#general-light').dispatchEvent('input');
  await page.locator('#general-light').dispatchEvent('change');
  await page.locator('[data-category=Persone]').click();
  await page.locator('[data-add=person-wheelchair]').click();
  await page.waitForFunction(()=>document.querySelector('#scene').dataset.loadingModels==='0',null,{timeout:60000});
  await page.locator('[data-category=Comunicazione]').click();
  await page.locator('[data-add=panel]').click();
  assert.ok(await page.locator('.visual-content [data-action=replace-image]').isVisible());
  await page.screenshot({path:'test-results/release-editor.png'});
  await page.locator('.top-actions summary').click();
  await page.locator('[data-action=export]').click();
  const download=page.waitForEvent('download');
  await page.locator('[data-action=save-json]').click();
  await (await download).saveAs('test-results/release-project.json');
  await page.goto(base+'/account');
  await page.locator('.account-form-card').waitFor();
  assert.deepEqual(errors,[]);
  assert.deepEqual(failed,[]);
  console.log('PASS production homepage, slider, mobile, templates, 3D tools, light, wheelchair, image upload control, export and account route.');
} finally {await browser.close();}
