import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProject,demo,item,validate,wallParts,openingFits,canWalk} from '../src/model.js';
import {Box3,Vector3,Group,Mesh,BoxGeometry,MeshBasicMaterial} from 'three';
import {fitPerson} from '../src/people-loader.js';
import {peopleCatalog,sizePerson} from '../src/people-catalog.js';
import {surface,preset,surfaceRows,validateSurface,FLOOR_ID} from '../src/surfaces.js';
import {surfaceUV} from '../src/surface-renderer.js';
test('conversione vecchio parquet al modulo PBR una sola volta',()=>{const legacy={material:'oak',color:'#bd9364',scale:.2,finish:'satin',rotation:90};const upgraded=surface(legacy);assert.equal(upgraded.scale,1.8);assert.equal(upgraded.color,legacy.color);assert.equal(upgraded.rotation,90);assert.deepEqual(surface(upgraded),upgraded);assert.equal(legacy.scale,.2);});

test('vecchi progetti mantengono colore pavimento e pareti senza migrazioni distruttive',()=>{const p=createProject();p.floor='#ab1234';validate(p);assert.equal(surface(p.floorSurface,p.floor).color,'#ab1234');assert.equal(surfaceRows(p).length,9);assert.equal(surfaceRows(p)[1].material,'paint');assert.equal(p.floorSurface,undefined);});
test('materiali: facce indipendenti, scala e finitura conservate nel JSON',()=>{const p=createProject();p.floorSurface=preset('oak');p.walls[0].surfaces={a:preset('concrete'),b:preset('plaster')};const copy=validate(JSON.parse(JSON.stringify(p)));assert.equal(copy.floorSurface.scale,1.8);assert.equal(copy.walls[0].surfaces.a.material,'concrete');assert.equal(copy.walls[0].surfaces.b.material,'plaster');for(const change of [{scale:0},{scale:Infinity},{rotation:NaN},{material:'url'},{color:'red'},{finish:'unknown'}])assert.throws(()=>validateSurface({...preset('oak'),...change}),/Materiale non valido/);p.objects=[{...item('bench'),id:FLOOR_ID}];assert.throws(()=>validate(p),/Identificatori/);});
test('UV in metri: la trama attraversa le porzioni della parete senza ripartire',()=>{const first=new BoxGeometry(2,3,.2),second=new BoxGeometry(2,3,.2);surfaceUV(first,{x:1,y:1.5,z:0});surfaceUV(second,{x:3,y:1.5,z:0});const edgeUV=(g,localX)=>{const out=[];for(let i=0;i<g.attributes.position.count;i++)if(g.attributes.normal.getZ(i)===1&&g.attributes.position.getX(i)===localX)out.push(g.attributes.uv.getX(i));return out;};assert.deepEqual(edgeUV(first,1),[2,2]);assert.deepEqual(edgeUV(second,-1),[2,2]);first.dispose();second.dispose();});
import {footprint,containsPoint,volumesOverlap,projectChecks,resizeRoom,setWallLength,measurementSVG} from '../src/planning.js';

test('ingombri ruotati: selezione e intersezioni usano la stessa orientazione del 3D',()=>{const a={...item('bench'),w:4,d:.2,rotation:45};const b={...a,z:.5};assert.equal(volumesOverlap(a,b),false);assert.equal(containsPoint(a,1,-1),true);assert.equal(containsPoint(a,1,1),false);assert.ok(footprint(a).some(p=>p.x>1.4&&p.z<0));b.z=.1;assert.equal(volumesOverlap(a,b),true);});
test('un appoggio non è una sovrapposizione: scultura sul piedistallo',()=>{const a=item('plinth'),b={...item('sculpture'),y:a.h};assert.equal(volumesOverlap(a,b),false);b.y-=.05;assert.equal(volumesOverlap(a,b),true);});
test('controlli geometrici rispettano i vuoti delle porte e la quota degli architravi',()=>{const p=createProject();p.walls=[{id:'wall',ax:-3,az:0,bx:3,bz:0,height:3,thickness:.2,openings:[{id:'door',type:'door',offset:2.5,width:1,height:2.1,sill:0}]}];p.objects=[{...item('scenery'),w:.5,d:.5,h:1}];assert.equal(projectChecks(p).length,0);p.objects[0].h=2.4;assert.ok(projectChecks(p).some(i=>i.title==='Intersezione con parete'));p.objects[0].x=8;assert.ok(projectChecks(p).some(i=>i.title==='Fuori dal pavimento'));});
test('ridimensionare la sala sposta il perimetro senza scalare gli elementi',()=>{const p=createProject(12,9);p.objects=[item('bench',2,1)];resizeRoom(p,'width',16);assert.equal(p.walls[0].ax,-8);assert.equal(p.walls[1].ax,8);assert.equal(p.walls[0].az,-4.5);assert.equal(p.objects[0].x,2);assert.equal(p.objects[0].w,1.6);validate(p);setWallLength(p.walls[0],10);assert.equal(p.walls[0].bx,2);});
test('quote persistenti: esportazione metrica e validazione input',()=>{const p=createProject();p.measurements=[{id:'m1',ax:0,az:0,bx:3,bz:4}];validate(p);assert.match(measurementSVG(p),/5.00 m/);p.measurements[0].bx=Infinity;assert.throws(()=>validate(p),/Quota non valida/);p.measurements[0].bx=3;p.measurements[0].id=p.walls[0].id;assert.throws(()=>validate(p),/Identificatori/);});
test('GLB: normalizzazione uniforme, altezza esatta e appoggio a terra',()=>{const source=new Group();const mesh=new Mesh(new BoxGeometry(.6,1.8,.3),new MeshBasicMaterial());mesh.position.set(4,-2,3);source.add(mesh);for(const h of [1.15,1.7,2]){const figure=fitPerson(source,{h});figure.updateMatrixWorld(true);const bounds=new Box3().setFromObject(figure,true),size=bounds.getSize(new Vector3());for(const [actual,expected] of [[size.x,h/3],[size.y,h],[size.z,h/6],[bounds.min.y,0]])assert.ok(Math.abs(actual-expected)<1e-6,`${actual} != ${expected}`);assert.equal(source.children[0].position.y,-2);}});
test('sei persone nel catalogo, dimensioni proporzionali senza arrotondamenti cumulativi',()=>{assert.equal(peopleCatalog.length,6);for(const def of peopleCatalog){const person=item(def.type);sizePerson(person,1.9);sizePerson(person,1.75);assert.equal(person.w,def.w);assert.equal(person.d,def.d);}});
test('vecchie figure migrate mantenendo altezza e posizione',()=>{const p=createProject();const o={...item('person'),type:'person',name:'Persona in piedi',h:1.9,x:3,z:-2,rotation:45};p.objects=[o];validate(p);assert.equal(o.type,'person-casual-15');assert.equal(o.h,1.9);assert.equal(o.x,3);assert.equal(o.z,-2);assert.equal(o.rotation,45);});
test('miniature conservate nei progetti e negli ingombri della visita',()=>{const p=createProject();p.objects=['person','person-coat','person-child'].map((t,i)=>item(t,i*2,0));assert.equal(validate(JSON.parse(JSON.stringify(p))).objects.length,3);assert.equal(canWalk(p,0,0),false);assert.equal(canWalk(p,1,2),true);});
test('progetto demo valido e dimensioni opera in metri',()=>{assert.equal(validate(demo()).width,14);const art=item('art');assert.equal(art.w,1.2);assert.equal(art.h,.8);});
test('porta sottrae volume reale dalla parete',()=>{const w=createProject().walls[0];w.openings=[{id:'door',offset:2,width:1,height:2.1,sill:0,type:'door'}];const area=wallParts(w).reduce((s,p)=>s+(p.end-p.start)*(p.top-p.bottom),0);assert.ok(Math.abs(area-(12*3.2-2.1))<1e-9);});
test('rifiuta aperture sovrapposte e fuori altezza',()=>{let w=createProject().walls[0];let o={id:'a',offset:2,width:1,height:2.1,sill:0,type:'door'};w.openings=[o];assert.equal(openingFits(w,{...o,id:'b',offset:2.5}),false);assert.equal(openingFits(w,{...o,id:'b',offset:10,height:4}),false);});
test('rifiuta import non finiti, dimensioni negative e ID duplicati',()=>{let p=createProject();p.objects.push(item('art'));p.objects[0].w=-1;assert.throws(()=>validate(p));p.objects[0].w=1;p.objects[0].x=Infinity;assert.throws(()=>validate(p));p.objects[0].x=0;p.walls[1].id=p.walls[0].id;assert.throws(()=>validate(p));});
test('visita rispetta pareti, aperture e oggetti ruotati',()=>{const p=createProject();p.walls.push({id:'a',ax:-5,az:0,bx:5,bz:0,thickness:.15,height:3.2,openings:[{id:'b',type:'door',offset:4.5,width:1,height:2.1,sill:0}]});assert.equal(canWalk(p,0,0),true);assert.equal(canWalk(p,2,0),false);assert.equal(canWalk(p,10,0),false);let o=item('bench',2,2);o.rotation=90;p.objects.push(o);assert.equal(canWalk(p,2,2.5),false);assert.equal(canWalk(p,3,2),true);});
