import './landing.css';
import './landing-cinema.css';
import './landing-hero-refined.css';
import {createIcons,Scan,ArrowUpRight,ArrowRight,Play,PencilRuler,Layers,Footprints,Ruler,GraduationCap,Landmark,Glasses,Box,FolderOpen,Monitor,X,Menu,Check,ChevronDown,Map,History,Sparkles} from 'lucide';
const icons={Scan,ArrowUpRight,ArrowRight,Play,PencilRuler,Layers,Footprints,Ruler,GraduationCap,Landmark,Glasses,Box,FolderOpen,Monitor,X,Menu,Check,ChevronDown,Map,History,Sparkles};
const icon=name=>`<i data-lucide="${name}"></i>`;
const link=(href,text,style='solid',symbol='arrow-up-right')=>`<a class="button ${style}" href="${href}">${text}${icon(symbol)}</a>`;
const app=document.querySelector('#app');
document.body.classList.add('landing-page');
app.innerHTML=`<a class="skip" href="#contenuto">Vai al contenuto</a>
<header class="site-header"><a class="logo" href="/" aria-label="Spazio, homepage">${icon('scan')}spazio<span>STUDIO ESPOSITIVO</span></a><nav id="site-nav" aria-label="Navigazione principale"><a href="#come-funziona">Come funziona</a><a href="#per-chi">Per chi è</a><a href="#esperienza">L’esperienza</a></nav><div class="nav-actions"><a class="login-link" data-access href="/account">Login</a>${link('/account?mode=signup','Iscriviti')}<button class="menu-toggle" aria-label="Apri menu" aria-expanded="false" aria-controls="site-nav">${icon('menu')}</button></div></header>
<main id="contenuto"><section class="hero cinema-hero" aria-label="Progetta la tua mostra"><div class="hero-scenes" aria-hidden="true"><picture><source media="(max-width: 700px)" srcset="/marketing/hero-luce-mobile.webp"/><img class="hero-scene active" src="/marketing/hero-luce.webp" alt="" width="1920" height="1080" fetchpriority="high"/></picture><picture><source media="(max-width: 700px)" srcset="/marketing/hero-terra-mobile.webp"/><img class="hero-scene" src="/marketing/hero-terra.webp" alt="" width="1920" height="1080"/></picture><picture><source media="(max-width: 700px)" srcset="/marketing/hero-soglia-mobile.webp"/><img class="hero-scene" src="/marketing/hero-soglia.webp" alt="" width="1920" height="1080"/></picture></div><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow"><span class="status-dot"></span> IL TUO STUDIO ESPOSITIVO, NEL BROWSER</span><h1>Le idee meritano<br/>il loro <em>spazio.</em></h1><p>Dalla prima parete all’ultimo sguardo.<br/>Progetta la tua mostra e scoprila dall’interno.</p><div class="hero-actions">${link('/studio?start=new','Inizia a creare','light')}${link('/studio?example=colore-luci','Entra nello studio','outline','play')}</div><span class="hero-note">Puoi iniziare anche senza un account.</span></div><div class="hero-bottom"><a class="scroll-cue" href="#come-funziona"><span>↓</span> SCOPRI SPAZIO</a><div class="scene-selector" aria-label="Atmosfera della galleria"><button data-scene="0" aria-pressed="true"><small>01</small>Luce e scultura</button><button data-scene="1" aria-pressed="false"><small>02</small>Toni di terra</button><button data-scene="2" aria-pressed="false"><small>03</small>La sala blu</button><button id="motion-toggle" aria-label="Metti in pausa le animazioni" aria-pressed="false">Ⅱ</button></div></div><span class="concept-credit">Abitare il colore · viste reali della mostra in Spazio</span></section>
<section class="intro-line"><span>UNO SPAZIO. TUTTE LE TUE POSSIBILITÀ.</span><p>Immagina liberamente.<br/><em>Progetta con precisione.</em></p><div>Musei e curatori<br/>Progettisti<br/>Scuole e università</div></section>
<section id="inizia" class="start-section" aria-labelledby="start-heading"><div class="start-heading"><div><span class="eyebrow">IL TUO PROSSIMO SPAZIO, INIZIA QUI</span><h2 id="start-heading">Una mostra da immaginare.<br/>Uno spazio da vivere.</h2></div><p>Disegna l’ambiente, allestisci le tue idee,<br/>esplorale in prima persona.</p></div><div class="start-grid"><a class="start-card" href="/studio?start=new"><span class="start-icon">${icon('pencil-ruler')}</span><h3>Crea uno spazio</h3><p>Parti da una stanza vuota.<br/>Ogni misura la decidi tu.</p><span class="start-card-action">Inizia da zero ${icon('arrow-up-right')}</span></a><a class="start-card" href="/studio?start=reference"><span class="start-icon">${icon('map')}</span><h3>Parti da una planimetria</h3><p>Importa una pianta reale<br/>e ricostruisci il tuo ambiente.</p><span class="start-card-action">Importa un riferimento ${icon('arrow-up-right')}</span></a></div><div class="start-links"><a href="/studio?start=demo">${icon('sparkles')} Esplora la mostra di esempio</a><button id="open-project" type="button">${icon('folder-open')} Apri file progetto</button><a id="resume-project" href="/studio?start=resume" hidden>${icon('history')}<span>Riprendi il progetto</span></a></div><p class="start-local-note">I tuoi progetti restano su questo dispositivo. Esportali per conservarne una copia.</p><p id="start-status" role="status" aria-live="polite"></p><input id="project-file" type="file" accept=".json" hidden/></section>
<div class="principles"><span>${icon('pencil-ruler')} Dal 2D al 3D</span><span>${icon('ruler')} Misure reali</span><span>${icon('layers')} Allestimenti flessibili</span><span>${icon('footprints')} Visita in prima persona</span></div>
<section id="come-funziona" class="section workflow-section"><div class="section-heading"><div><span class="eyebrow">UN PERCORSO NATURALE</span><h2>Tre passi.<br/>Infinite possibilità.</h2></div><p>Non serve pensare come un software 3D.<br/>Basta pensare alla mostra che vuoi creare.</p></div><div class="steps"><article><div class="step-top"><span>01</span>${icon('pencil-ruler')}</div><h3>Crea il tuo spazio.</h3><p>Parti da una stanza vuota o da una planimetria reale. Disegna pareti, porte e aperture, con le misure che ti servono.</p><a href="/studio?start=new">Dal primo metro ${icon('arrow-right')}</a></article><article><div class="step-top"><span>02</span>${icon('layers')}</div><h3>Dai forma alla mostra.</h3><p>Aggiungi opere, teche, pannelli e arredi. Scegli dimensioni, materiali e altezze. Prova, sposta, ripensa.</p><a href="/studio?start=demo">Dentro l’editor ${icon('arrow-right')}</a></article><article><div class="step-top"><span>03</span>${icon('footprints')}</div><h3>Guardala da dentro.</h3><p>Entra nello spazio e percorri la mostra. Osserva le distanze, gli ingombri e il dialogo tra le opere.</p><a href="/studio?start=visit">Entra nella visita ${icon('arrow-right')}</a></article></div></section>
<section id="esperienza" class="experience-section"><div class="experience-copy"><span class="eyebrow">DAL DISEGNO ALLA VISITA</span><h2>Non limitarti<br/>a immaginarla.<br/><em>Entraci.</em></h2><p>Quanto spazio c’è tra due opere? Come cambia il percorso con una parete in più? Esplora il tuo allestimento in prima persona e trova il punto di vista giusto.</p><ul><li>${icon('check')} Dimensioni e distanze in metri</li><li>${icon('check')} Opere, arredi e persone in scala</li><li>${icon('check')} Materiali, colori e luce</li></ul>${link('/studio?example=colore-luci','Esplora la mostra','light','footprints')}</div><figure class="walk-figure"><img src="/marketing/hero-luce.webp" alt="La mostra Abitare il colore in Spazio, con fari orientabili e scultura centrale" loading="lazy" width="1920" height="1080"/><a class="walk-link" href="/studio?example=colore-luci" aria-label="Apri la mostra illuminata nell’editor">${icon('arrow-up-right')}</a><figcaption><span>UN ALTRO PUNTO DI VISTA</span><small>Vista reale della mostra in Spazio</small></figcaption></figure></section>
<section class="finish-story"><div><span class="eyebrow">LA MATERIA FA LA DIFFERENZA</span><h2>Lo stesso spazio.<br/>Un’altra atmosfera.</h2><p>Legno, pietra, cemento. Scegli materiali e colori per pavimenti, pareti e arredi, e guarda come cambia la tua mostra.</p><a class="finish-link" href="/studio?start=demo">Esplora i materiali ${icon('arrow-up-right')}</a></div><div class="finish-samples">${[['WoodFloor051','01','Legno','Caldo. Naturale.'],['Marble012','02','Marmo','Luce e carattere.'],['Concrete034','03','Cemento','Essenziale. Materico.'],['Terrazzo001','04','Terrazzo','Dettagli che raccontano.']].map(([asset,n,name,caption])=>`<figure><div><img src="/materials/${asset}/preview.webp" loading="lazy" alt="Campione di ${name.toLowerCase()} disponibile nello studio" width="256" height="256"/><span>${n}</span></div><figcaption><b>${name}</b><small>${caption}</small></figcaption></figure>`).join('')}</div></section>
<section id="per-chi" class="section audience-section"><div class="section-heading"><div><span class="eyebrow">MODI DIVERSI DI IMMAGINARE</span><h2>Il tuo progetto.<br/>Il tuo punto di vista.</h2></div><p>Dalla prima attività in classe<br/>alla progettazione di una mostra reale.</p></div><div class="audience-cards"><article>${icon('landmark')}<h3>Per musei e curatori</h3><p>Metti in relazione opere e ambienti. Valuta il percorso e confronta diverse ipotesi di allestimento prima di costruire.</p><span>DARE SPAZIO A UNA STORIA</span></article><article>${icon('pencil-ruler')}<h3>Per chi progetta</h3><p>Trasforma le misure in uno spazio navigabile. Sperimenta materiali, volumi e posizioni, poi esporta il tuo progetto.</p><span>RENDERE VISIBILE UN’IDEA</span></article><article>${icon('graduation-cap')}<h3>Per chi insegna e impara</h3><p>Una mostra sull’Antico Egitto? 200 m² di Impressionismo? Impara a comunicare progettando uno spazio concreto.</p><span>IMPARARE FACENDO</span></article></div></section>
<section class="immersive"><div class="immersive-title">${icon('glasses')}<span class="eyebrow">CAMBIA PUNTO DI VISTA</span><h2>Non solo da vedere.<br/>Da attraversare.</h2></div><div class="immersive-copy"><p>La visita in prima persona ti porta tra le opere. Sui dispositivi WebXR compatibili, puoi esplorare la mostra in VR o osservarla come plastico in AR.</p>${link('/studio?example=colore-luci','Esplora la mostra','outline','footprints')}<small>VR e AR richiedono hardware e browser compatibili. La modalità AR attuale è un plastico, non una sovrapposizione in scala reale.</small></div></section>
<section class="section faq-section"><div><span class="eyebrow">PRIMA DI ENTRARE</span><h2>Qualche risposta.<br/>Poi, spazio alle idee.</h2></div><div class="faq-list"><details><summary>Devo conoscere un software 3D? ${icon('chevron-down')}</summary><p>No. Puoi partire dalle dimensioni della stanza, aggiungere gli elementi dal catalogo e modificarli con misure numeriche o trascinandoli nella scena.</p></details><details><summary>Posso usare una planimetria esistente? ${icon('chevron-down')}</summary><p>Sì. Carica un’immagine JPG, PNG o WebP, indica la larghezza reale dell’immagine e ricalca le pareti. L’importazione attuale è un riferimento da ricostruire manualmente.</p></details><details><summary>Serve un account? Dove vengono salvati i progetti? ${icon('chevron-down')}</summary><p>In questa versione puoi lavorare senza account. Il progetto viene salvato nel browser su questo dispositivo. Esporta il file progetto per conservarlo o trasferirlo. L’area personale permette di salvare online progetti e contenuti quando il servizio account è attivato. Il salvataggio online si avvia dallo studio con “Salva online”.</p></details><details><summary>Posso portare il progetto fuori da Spazio? ${icon('chevron-down')}</summary><p>Sì. Puoi esportare il file progetto con gli asset, la planimetria SVG, l’elenco degli elementi CSV, screenshot e una scheda di allestimento stampabile.</p></details></div></section>
<section class="closing"><span class="eyebrow">IL PROSSIMO SPAZIO È IL TUO</span><h2>Cosa metterai<br/>in mostra?</h2>${link('/studio?start=new','Crea la tua prima mostra','light')}<p>Una stanza vuota è già un inizio.</p></section></main>
<footer class="site-footer"><a class="logo footer-logo" href="/">${icon('scan')}spazio</a><span>Immagina. Progetta. Abita.</span><div><a href="#come-funziona">Come funziona</a><button class="text-button" data-access>Accedi allo studio</button></div><small>© ${new Date().getFullYear()} Spazio · Studio espositivo</small></footer>
`;
document.querySelector('.finish-story').after(document.querySelector('#inizia'));
document.querySelectorAll('[data-access]').forEach(b=>b.addEventListener('click',()=>location.assign('/account')));
const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Chiudi menu':'Apri menu');document.querySelector('#site-nav').classList.toggle('open',open);});document.querySelectorAll('#site-nav a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');document.querySelector('#site-nav').classList.remove('open');}));
createIcons({icons,attrs:{'stroke-width':1.65}});
// Main calls to action lead to the two starting choices within the homepage.
document.querySelectorAll('.nav-actions a[href*="start=new"],.hero-actions a[href*="start=new"],.closing a[href*="start=new"]').forEach(a=>a.href='#inizia');
let landingDatabase;
const databaseReady=new Promise(resolve=>{const req=indexedDB.open('spazio-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('projects');req.onsuccess=()=>{landingDatabase=req.result;resolve(landingDatabase);const read=landingDatabase.transaction('projects').objectStore('projects').get('current');read.onsuccess=()=>{const project=read.result;if(project?.version===1&&typeof project.name==='string'){const resume=document.querySelector('#resume-project');resume.hidden=false;resume.querySelector('span').textContent='Riprendi: '+project.name;}};};req.onerror=()=>resolve(null);});
const projectInput=document.querySelector('#project-file'),openProject=document.querySelector('#open-project'),status=document.querySelector('#start-status');
openProject.addEventListener('click',()=>{projectInput.value='';projectInput.click();});
projectInput.addEventListener('change',async()=>{const file=projectInput.files[0];if(!file)return;openProject.disabled=true;status.textContent='Apertura del progetto…';try{if(file.size>150*1024*1024)throw Error('Il file supera il limite di 150 MB.');const {validate}=await import('./model.js');const project=validate(JSON.parse(await file.text()));const db=await databaseReady;if(!db)throw Error('Salvataggio locale non disponibile in questo browser.');await new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(project,'current');tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(Error('Impossibile salvare il progetto sul dispositivo.'));});location.assign('/studio?start=resume');}catch(error){status.textContent=error instanceof SyntaxError?'Il file non contiene un progetto Spazio valido.':error.message;openProject.disabled=false;}});

import('./landing-motion.js');
