import {readProjectFile} from './project-file.js';
import {producer} from './producer.js';
import './landing.css';
import './landing-education.css';
import './landing-slider.css';
import {createIcons,Scan,ArrowUpRight,ArrowRight,Play,PencilRuler,Layers,Footprints,FolderOpen,Menu,Map,History,Sparkles} from 'lucide';
const icons={Scan,ArrowUpRight,ArrowRight,Play,PencilRuler,Layers,Footprints,FolderOpen,Menu,Map,History,Sparkles};
const icon=name=>`<i data-lucide="${name}"></i>`;
const link=(href,text,style='solid',symbol='arrow-up-right')=>`<a class="button ${style}" href="${href}">${text}${icon(symbol)}</a>`;
const app=document.querySelector('#app');
document.body.classList.add('landing-page');
app.innerHTML=`
<a class="skip" href="#contenuto">Vai al contenuto</a>
<header class="site-header"><a class="logo" href="/" aria-label="exhibitionLab, homepage">${icon('scan')}<b class=brand-word>exhibition<em>Lab</em></b></a><nav id="site-nav" aria-label="Navigazione principale"><a href="/templates">Template</a><a href="#come-funziona">Come funziona</a></nav><div class="nav-actions"><a class="login-link" data-access href="/account">Accedi</a><button class="menu-toggle" aria-label="Apri menu" aria-expanded="false" aria-controls="site-nav">${icon('menu')}</button></div></header>
<main id="contenuto">
<section class="hero cinema-hero" aria-label="Progetta la tua mostra"><div class="hero-scenes" aria-hidden="true"><picture><source media="(max-width: 700px)" srcset="/marketing/exhibitionlab-classroom-v2-small.webp"/><img class="hero-scene active" src="/marketing/exhibitionlab-classroom-v2.webp" alt="" width="1672" height="941" fetchpriority="high"/></picture><picture><source media="(max-width: 700px)" srcset="/marketing/hero-terra-mobile.webp"/><img class="hero-scene" src="/marketing/hero-terra.webp" alt="" width="1920" height="1080"/></picture><picture><source media="(max-width: 700px)" srcset="/marketing/hero-soglia-mobile.webp"/><img class="hero-scene" src="/marketing/hero-soglia.webp" alt="" width="1920" height="1080"/></picture></div><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow"><span class="status-dot"></span> UN LABORATORIO DIDATTICO, NEL BROWSER</span><h1>Configuratore virtuale <br/>di <em>mostre e spazi espositivi.</em></h1><p>Impara progettando una mostra in 3D.<br/>Un laboratorio didattico per esplorare arte, spazio e allestimento.</p><div class="hero-actions">${link('#inizia','Inizia a creare','light')}${link('/studio?example=colore-luci','Entra nello studio','outline','play')}</div><span class="hero-note">Puoi iniziare anche senza un account.</span></div><div class="hero-bottom"><a class="scroll-cue" href="#come-funziona"><span>↓</span> SCOPRI EXHIBITIONLAB</a><div class="scene-selector" aria-label="Immagini di exhibitionLab"><button data-scene="0" aria-pressed="true"><small>01</small>In classe</button><button data-scene="1" aria-pressed="false"><small>02</small>Toni di terra</button><button data-scene="2" aria-pressed="false"><small>03</small>La sala blu</button><button id="motion-toggle" aria-label="Metti in pausa le animazioni" aria-pressed="false">Ⅱ</button></div></div><span class="concept-credit">In classe: immagine illustrativa · Gallerie: viste della mostra</span></section>
<section id="come-funziona" class="education-how" aria-labelledby="how-title"><div class="education-intro"><div><span class="eyebrow">IL LABORATORIO DIGITALE</span><h2 id="how-title">Un laboratorio digitale per la progettazione di mostre</h2></div><p>exhibitionLab è un ambiente 3D per attività didattiche dedicate alla progettazione di mostre virtuali. Il docente può proporre un tema e guidare gli studenti nella selezione delle opere, nell’organizzazione degli spazi e nella definizione di un percorso espositivo. Il progetto offre una base per collegare ricerca sui contenuti, scelte di allestimento e discussione in classe.</p></div><div class="steps"><article><span class="step-number">1</span><h3>Progettazione dello spazio</h3><p>La costruzione dell’ambiente permette di lavorare su misure, proporzioni e organizzazione dei percorsi.</p></article><article><span class="step-number">2</span><h3>Selezione e contestualizzazione</h3><p>La scelta e la disposizione delle opere richiedono di approfondire i contenuti e stabilire relazioni coerenti con il tema proposto.</p></article><article><span class="step-number">3</span><h3>Osservazione e confronto</h3><p>La visita in 3D consente di esaminare l’allestimento, discutere le scelte e individuare possibili revisioni. VR e AR sono disponibili sui dispositivi compatibili.</p></article></div></section>
<section id="inizia" class="education-start" aria-labelledby="start-heading"><div class="start-heading"><h2 id="start-heading">Inizia da qui</h2><p>Scegli una stanza vuota, una planimetria da ricalcare o un template da modificare.</p></div><div class="start-options-grid"><a class="start-card" href="/studio?start=new"><img class="start-photo" src="/marketing/start-empty-room.webp" alt="Stanza vuota nell’editor 3D" loading="lazy" width="800" height="450"/><div class="start-card-content"><h3>Parti da zero</h3><p>Definisci le dimensioni della stanza e comincia ad allestire.</p><span class="start-card-action">Crea una mostra ${icon('arrow-up-right')}</span></div></a><a class="start-card" href="/studio?start=reference"><img class="start-photo" src="/marketing/start-plan.webp" alt="Planimetria disegnata a mano da usare come riferimento" loading="lazy" width="800" height="450"/><div class="start-card-content"><h3>Usa una planimetria</h3><p>Carica una pianta JPG, PNG o WebP e ricalca le pareti.</p><span class="start-card-action">Importa una pianta ${icon('arrow-up-right')}</span></div></a><a class="start-card" href="/templates"><img class="start-photo" src="/templates/colore-luci.webp" alt="Mostra allestita disponibile tra i template" loading="lazy" width="800" height="450"/><div class="start-card-content"><h3>Parti da un template</h3><p>Scegli una mostra già allestita e adattala al tuo progetto.</p><span class="start-card-action">Sfoglia i template ${icon('arrow-up-right')}</span></div></a></div><div class="start-links"><button id="open-project" type="button">${icon('folder-open')} Apri file progetto</button><a id="resume-project" href="/studio?start=resume" hidden>${icon('history')}<span>Riprendi il progetto</span></a></div><p class="start-local-note">I progetti si salvano nel browser. Esporta una copia per conservarli.</p><p id="start-status" role="status" aria-live="polite"></p><input id="project-file" type="file" accept=".json,.glb" hidden/></section>

</main><footer class="site-footer"><div><a class="logo" href="/">exhibitionLab</a><span>Configuratore virtuale di mostre</span></div><div class="footer-links"><a href="/account">Area personale</a><a href="/templates">Template</a></div><small>© ${new Date().getFullYear()} exhibitionLab · Un progetto per la didattica</small>${producer()}</footer>`;

document.querySelectorAll('[data-access]').forEach(b=>b.addEventListener('click',()=>location.assign('/account')));
const toggle=document.querySelector('.menu-toggle');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Chiudi menu':'Apri menu');document.querySelector('#site-nav').classList.toggle('open',open);});document.querySelectorAll('#site-nav a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');document.querySelector('#site-nav').classList.remove('open');}));
createIcons({icons,attrs:{'stroke-width':1.65}});
// Main calls to action lead to the two starting choices within the homepage.
document.querySelectorAll('.nav-actions a[href*="start=new"],.hero-actions a[href*="start=new"],.closing a[href*="start=new"]').forEach(a=>a.href='#inizia');
let landingDatabase;
const databaseReady=new Promise(resolve=>{const req=indexedDB.open('spazio-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('projects');req.onsuccess=()=>{landingDatabase=req.result;resolve(landingDatabase);const read=landingDatabase.transaction('projects').objectStore('projects').get('current');read.onsuccess=()=>{const project=read.result;if(project?.version===1&&typeof project.name==='string'){const resume=document.querySelector('#resume-project');resume.hidden=false;resume.querySelector('span').textContent='Riprendi: '+project.name;}};};req.onerror=()=>resolve(null);});
const projectInput=document.querySelector('#project-file'),openProject=document.querySelector('#open-project'),status=document.querySelector('#start-status');
openProject.addEventListener('click',()=>{projectInput.value='';projectInput.click();});
projectInput.addEventListener('change',async()=>{const file=projectInput.files[0];if(!file)return;openProject.disabled=true;status.textContent='Apertura del progetto…';try{if(file.size>150*1024*1024)throw Error('Il file supera il limite di 150 MB.');const project=await readProjectFile(file);const db=await databaseReady;if(!db)throw Error('Salvataggio locale non disponibile in questo browser.');await new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(project,'current');tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(Error('Impossibile salvare il progetto sul dispositivo.'));});location.assign('/studio?start=resume');}catch(error){status.textContent=error instanceof SyntaxError?'Il file non contiene un progetto exhibitionLab valido.':error.message;openProject.disabled=false;}});



import('./landing-slider.js');
