export const materials=[
 {id:'paint',name:'Tinta unita',category:'Pareti',color:'#f6f5f0',scale:1,finish:'matte'},
 {id:'plaster',name:'Intonaco minerale',category:'Pareti',asset:'Plaster001',color:'#ffffff',scale:1,finish:'matte'},
 {id:'oak',name:'Parquet chiaro',category:'Legni',asset:'WoodFloor051',color:'#ffffff',scale:1.8,finish:'satin'},
 {id:'concrete',name:'Cemento liscio',category:'Cementi',asset:'Concrete034',color:'#ffffff',scale:1.1,aspect:.5,finish:'matte'},
 {id:'resin',name:'Resina continua',category:'Cementi',color:'#c8c5b9',scale:1,finish:'satin'},
 {id:'carpet',name:'Tessuto grigio',category:'Tessuti',asset:'Fabric030',color:'#ffffff',scale:.5,finish:'matte'},
 {id:'stone',name:'Marmo chiaro',category:'Pietre',asset:'Marble012',color:'#ffffff',scale:2,finish:'satin'},
 {id:'metal',name:'Metallo satinato',category:'Metalli',asset:'Metal032',color:'#ffffff',scale:1,finish:'satin',metalness:.85},
 {id:'dark-parquet',name:'Parquet scuro',category:'Legni',asset:'WoodFloor064',color:'#ffffff',scale:2,finish:'satin'},
 {id:'natural-parquet',name:'Doghe rustiche',category:'Legni',asset:'WoodFloor043',color:'#ffffff',scale:1.3,aspect:.5,finish:'satin'},
 {id:'dark-wood',name:'Legno venato',category:'Legni',asset:'Wood051',color:'#ffffff',scale:.8,finish:'satin'},
 {id:'painted-plaster',name:'Intonaco dipinto',category:'Pareti',asset:'PaintedPlaster017',color:'#ffffff',scale:1,finish:'matte'},
 {id:'concrete-slabs',name:'Lastre di cemento',category:'Cementi',asset:'Concrete031',color:'#ffffff',scale:2,finish:'matte'},
 {id:'dark-marble',name:'Marmo scuro',category:'Pietre',asset:'Marble006',color:'#ffffff',scale:2,finish:'gloss'},
 {id:'terrazzo',name:'Terrazzo veneziano',category:'Pietre',asset:'Terrazzo001',color:'#ffffff',scale:1,finish:'satin'},
 {id:'white-tiles',name:'Piastrelle bianche',category:'Piastrelle',asset:'Tiles107',color:'#ffffff',scale:1,finish:'gloss'},
 {id:'dark-tiles',name:'Pietra a mosaico',category:'Pietre',asset:'Tiles093',color:'#ffffff',scale:2.45,finish:'matte'},
 {id:'woven-fabric',name:'Tessuto intrecciato',category:'Tessuti',asset:'Fabric019',color:'#ffffff',scale:.5,finish:'matte'},
 {id:'worked-metal',name:'Metallo dorato',category:'Metalli',asset:'Metal007',color:'#ffffff',scale:1,finish:'satin',metalness:.9},
 {id:'brick',name:'Mattoni a vista',category:'Pareti',asset:'Bricks097',color:'#ffffff',scale:2,finish:'matte'},
];
