import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {wallParts,wallLength,canWalk} from './model.js';
import {createPerson} from './people-loader.js';
export class StudioScene{
 constructor(host,onSelect,onMove,notify){this.host=host;this.onSelect=onSelect;this.onMove=onMove;this.notify=notify;this.scene=new T.Scene();this.scene.background=new T.Color('#e9eae6');this.camera=new T.PerspectiveCamera(45,1,.05,400);this.camera.position.set(15,14,18);this.renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.renderer.xr.enabled=true;host.append(this.renderer.domElement);this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.maxPolarAngle=Math.PI*.48;this.orbit.minDistance=2;this.orbit.maxDistance=120;this.orbit.target.set(0,0,0);
 this.scene.add(new T.HemisphereLight(0xffffff,0x8b8b7f,2.5));let sun=new T.DirectionalLight(0xfff8e9,3);sun.position.set(-4,16,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:30,bottom:-30});sun.shadow.bias=-.0005;this.scene.add(sun);this.world=new T.Group();this.scene.add(this.world);this.rig=new T.Group();this.scene.add(this.rig);this.rig.add(this.camera);
 this.transform=new TransformControls(this.camera,this.renderer.domElement);this.transform.setSize(.7);this.transform.setTranslationSnap(.05);this.scene.add(this.transform.getHelper());this.transform.addEventListener('dragging-changed',e=>this.orbit.enabled=!e.value);this.transform.addEventListener('mouseUp',()=>{const g=this.transform.object;if(g)this.onMove(g.userData.id,{x:g.position.x,z:g.position.z,y:Math.max(0,g.position.y),rotation:g.rotation.y*180/Math.PI});});this.transform.showY=false;
 this.keys={};this.yaw=0;this.pitch=0;this.clock=new T.Clock();this.videos=[];this.generation=0;this.ar=false;
 this.renderer.domElement.addEventListener('pointerdown',e=>{this.pointer={x:e.clientX,y:e.clientY};this.look={x:e.clientX,y:e.clientY};if(this.visit)this.renderer.domElement.setPointerCapture(e.pointerId);});this.renderer.domElement.addEventListener('pointermove',e=>{if(this.visit&&this.look&&e.buttons){this.yaw-=(e.clientX-this.look.x)*.004;this.pitch=Math.max(-1.3,Math.min(1.3,this.pitch-(e.clientY-this.look.y)*.004));this.look={x:e.clientX,y:e.clientY};}});
 this.renderer.domElement.addEventListener('pointerup',e=>{this.look=null;if(this.visit||this.transform.dragging||!this.pointer||Math.hypot(e.clientX-this.pointer.x,e.clientY-this.pointer.y)>5||this.transform.axis)return;const r=host.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);let hit=ray.intersectObjects(this.objects.children,true)[0];if(hit){let g=hit.object;while(g&&!g.userData.id)g=g.parent;if(g)this.onSelect(g.userData.id);}else this.onSelect(null);});
 window.addEventListener('keydown',e=>{if(!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){this.keys[e.code]=true;if(this.visit&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();}});window.addEventListener('keyup',e=>this.keys[e.code]=false);window.addEventListener('blur',()=>this.keys={});new ResizeObserver(()=>this.resize()).observe(host);this.renderer.setAnimationLoop((_,frame)=>this.frame(frame));
 this.renderer.xr.addEventListener('sessionend',()=>{this.ar=false;this.world.scale.setScalar(1);this.world.position.set(0,0,0);this.world.rotation.set(0,0,0);this.scene.background=new T.Color('#e9eae6');this.rig.position.set(0,0,0);this.setVisit(true);});
 }
 resize(){let r=this.host.getBoundingClientRect();if(!r.width||!r.height)return;this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.renderer.setSize(r.width,r.height);}
 material(c,props={}){return new T.MeshStandardMaterial({color:c,roughness:.8,...props});}
 box(parent,w,h,d,x,y,z,color,props={}){let m=new T.Mesh(new T.BoxGeometry(w,h,d),this.material(color,props));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 clear(){this.transform.detach();this.videos.forEach(v=>{v.pause();v.removeAttribute('src');v.load();});this.videos=[];this.world.traverse(o=>{if(o.userData.sharedPersonAsset)return;o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});this.world.clear();}
 build(p){this.project=p;const generation=++this.generation;this.clear();this.pendingModels=0;this.host.dataset.loadingModels='0';this.box(this.world,p.width,.12,p.depth,0,-.06,0,p.floor);let grid=new T.GridHelper(Math.max(p.width,p.depth),Math.max(p.width,p.depth)*2,0xb9bcb3,0xd0d2cb);grid.position.y=.003;grid.material.transparent=true;grid.material.opacity=.35;grid.visible=!this.visit;this.grid=grid;this.world.add(grid);
 this.walls=new T.Group();this.world.add(this.walls);for(const w of p.walls){let g=new T.Group(),len=wallLength(w);g.position.set(w.ax,0,w.az);g.rotation.y=-Math.atan2(w.bz-w.az,w.bx-w.ax);g.userData.wall=w;for(const s of wallParts(w))this.box(g,s.end-s.start,s.top-s.bottom,w.thickness,(s.start+s.end)/2,(s.top+s.bottom)/2,0,'#f6f5f0');for(const o of w.openings){if(o.type==='window')this.box(g,o.width,o.height,.025,o.offset+o.width/2,o.sill+o.height/2,0,'#bcdce1',{transparent:true,opacity:.25,roughness:.1});}this.walls.add(g);}
 this.objects=new T.Group();this.world.add(this.objects);for(const o of p.objects){let g=new T.Group();g.position.set(o.x,o.y,o.z);g.rotation.y=o.rotation*Math.PI/180;g.userData.id=o.id;this.objects.add(g);const {w,h,d}=o;
 if(o.type.startsWith('person')){this.pendingModels++;this.host.dataset.loadingModels=String(this.pendingModels);createPerson(o).then(model=>{if(generation!==this.generation)return;g.add(model);g.userData.loadedModel=true;}).catch(()=>{if(generation===this.generation)this.notify('Impossibile caricare '+o.name+'. Riprova ricaricando la pagina.');}).finally(()=>{if(generation===this.generation){this.pendingModels--;this.host.dataset.loadingModels=String(this.pendingModels);}});}
 else if(o.type==='bench'||o.type==='desk'){this.box(g,w,.12,d,0,h-.06,0,o.color);[-1,1].forEach(s=>this.box(g,.08,h-.12,d*.8,s*(w/2-.13),(h-.12)/2,0,o.color));}
 else if(o.type==='case'){this.box(g,w,h*.55,d,0,h*.275,0,'#eeede7');this.box(g,w,h*.45,d,0,h*.775,0,o.color,{transparent:true,opacity:.24,roughness:.05,metalness:.15});}
 else if(o.type==='sculpture'){let mesh=new T.Mesh(new T.TorusKnotGeometry(.3,.11,96,16),this.material(o.color,{metalness:.35,roughness:.35}));mesh.geometry.computeBoundingBox();let b=mesh.geometry.boundingBox,size=b.getSize(new T.Vector3());mesh.scale.set(w/size.x,h/size.y,d/size.z);mesh.position.y=h/2;mesh.castShadow=true;g.add(mesh);}
 else if(o.type==='column'){let m=new T.Mesh(new T.CylinderGeometry(w/2,w/2,h,32),this.material(o.color));m.scale.z=d/w;m.position.y=h/2;m.castShadow=true;g.add(m);}
 else if(o.type==='structure'){[-1,1].forEach(s=>this.box(g,.06,h,d,s*(w/2-.03),h/2,0,o.color));[.04,h/2,h-.04].forEach(y=>this.box(g,w,.08,d,0,y,0,o.color));}
 else if(o.type==='light'){this.box(g,w,h,d,0,h/2,0,'#30372f');let light=new T.PointLight(o.color,o.intensity||8,8,2);light.position.y=-.05;g.add(light);}
 else if(o.type==='model'&&o.model){new GLTFLoader().load(o.model,res=>{if(generation!==this.generation)return;let b=new T.Box3().setFromObject(res.scene),size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3());res.scene.position.sub(center);let wrap=new T.Group();wrap.add(res.scene);wrap.scale.set(w/(size.x||1),h/(size.y||1),d/(size.z||1));wrap.position.y=h/2;wrap.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});g.add(wrap);},undefined,()=>this.notify('Modello non leggibile: usa un GLB con risorse incorporate.'));}
 else{this.box(g,w,h,d,0,h/2,0,o.type==='art'?'#373b35':o.color);if(['art','panel','sign','monitor'].includes(o.type)){let mat;if(o.image){const tex=new T.TextureLoader().load(o.image);tex.colorSpace=T.SRGBColorSpace;mat=new T.MeshBasicMaterial({map:tex});}else if(o.video){const v=document.createElement('video');v.src=o.video;v.loop=true;v.muted=true;v.playsInline=true;this.videos.push(v);if(this.visit)v.play().catch(()=>{});let tex=new T.VideoTexture(v);tex.colorSpace=T.SRGBColorSpace;mat=new T.MeshBasicMaterial({map:tex});}else if(o.text){const canvas=document.createElement('canvas');canvas.width=800;canvas.height=Math.round(800*h/w);const c=canvas.getContext('2d');c.fillStyle=o.color;c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle=o.type==='sign'?'#ffffff':'#25382f';c.font=`${o.type==='sign'?52:42}px Arial`;o.text.split('\n').slice(0,20).forEach((t,i)=>c.fillText(t,55,90+i*58,690));let tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;mat=new T.MeshBasicMaterial({map:tex});}else mat=this.material(o.color,{roughness:1});let face=new T.Mesh(new T.PlaneGeometry(w,h),mat);face.position.set(0,h/2,d/2+.002);g.add(face);}}
 }
 this.select(this.selected);}
 select(id){this.selected=id;this.transform.detach();if(this.selection){this.selection.removeFromParent();this.selection.geometry.dispose();this.selection.material.dispose();this.selection=null;}if(!id||this.visit)return;let obj=this.objects.children.find(g=>g.userData.id===id);if(obj){this.transform.attach(obj);this.selection=new T.BoxHelper(obj,0x527d58);this.scene.add(this.selection);}}
 setTool(mode){this.transform.setMode(mode);this.transform.showY=mode==='translate';if(mode==='rotate'){this.transform.showX=false;this.transform.showY=true;this.transform.showZ=false;this.transform.setRotationSnap(Math.PI/12);}else{this.transform.showX=true;this.transform.showZ=true;}}
 home(){this.camera.position.set(this.project.width*1.1,Math.max(this.project.width,this.project.depth),this.project.depth*1.5);this.orbit.target.set(0,0,0);this.orbit.update();}
 setVisit(v){this.camera.fov=v?70:45;this.camera.updateProjectionMatrix();this.visit=v;this.keys={};this.orbit.enabled=!v;if(v){this.editPos=this.camera.position.clone();this.editTarget=this.orbit.target.clone();let spawn={x:0,z:this.project.depth/2-1};if(!canWalk(this.project,spawn.x,spawn.z)){outer:for(let z=this.project.depth/2-.5;z>-this.project.depth/2;z-=.5)for(let x=-this.project.width/2+.5;x<this.project.width/2;x+=.5)if(canWalk(this.project,x,z)){spawn={x,z};break outer;}}this.camera.position.set(spawn.x,1.65,spawn.z);this.yaw=0;this.pitch=0;this.camera.rotation.set(0,0,0);this.transform.detach();this.selection?.removeFromParent();this.videos.forEach(v=>v.play().catch(()=>{}));}else{this.camera.position.copy(this.editPos||new T.Vector3(15,14,18));this.orbit.target.copy(this.editTarget||new T.Vector3());this.orbit.update();this.videos.forEach(v=>v.pause());this.select(this.selected);}if(this.grid)this.grid.visible=!v;}
 frame(frame){const dt=Math.min(this.clock.getDelta(),.05);if(this.visit&&!this.renderer.xr.isPresenting){if(this.keys.ArrowLeft)this.yaw+=dt*1.5;if(this.keys.ArrowRight)this.yaw-=dt*1.5;this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');let f=+(!!(this.keys.KeyW||this.keys.ArrowUp))-+(!!(this.keys.KeyS||this.keys.ArrowDown)),s=+(!!this.keys.KeyD)-+(!!this.keys.KeyA);if(f||s){const len=Math.hypot(f,s),v=dt*2.1/len,dx=(-Math.sin(this.yaw)*f+Math.cos(this.yaw)*s)*v,dz=(-Math.cos(this.yaw)*f-Math.sin(this.yaw)*s)*v;if(canWalk(this.project,this.camera.position.x+dx,this.camera.position.z))this.camera.position.x+=dx;if(canWalk(this.project,this.camera.position.x,this.camera.position.z+dz))this.camera.position.z+=dz;}}else if(!this.visit)this.orbit.update();
 if(this.walls)for(const g of this.walls.children){const w=g.userData.wall,outerZ=Math.abs(w.az-w.bz)<.01&&Math.abs(Math.abs(w.az)-this.project.depth/2)<.01,outerX=Math.abs(w.ax-w.bx)<.01&&Math.abs(Math.abs(w.ax)-this.project.width/2)<.01;const facing=outerZ&&Math.sign(w.az)*this.camera.position.z>this.project.depth/2||outerX&&Math.sign(w.ax)*this.camera.position.x>this.project.width/2;g.visible=this.visit||!this.cutaway||!facing;}
 if(this.renderer.xr.isPresenting&&!this.ar){for(const source of this.renderer.xr.getSession().inputSources){const axes=source.gamepad?.axes;if(axes?.length>=4){const cam=this.renderer.xr.getCamera(),dir=new T.Vector3();cam.getWorldDirection(dir);dir.y=0;dir.normalize();const side=new T.Vector3().crossVectors(dir,new T.Vector3(0,1,0));const dx=(dir.x*-axes[3]+side.x*axes[2])*dt*1.6,dz=(dir.z*-axes[3]+side.z*axes[2])*dt*1.6;let pos=cam.getWorldPosition(new T.Vector3());if(canWalk(this.project,pos.x+dx,pos.z+dz)){this.rig.position.x+=dx;this.rig.position.z+=dz;}}}}
 this.selection?.update();this.renderer.render(this.scene,this.camera);}
 async immersive(mode){if(!navigator.xr||!await navigator.xr.isSessionSupported(mode)){this.notify(mode==='immersive-vr'?'VR non disponibile: apri con un browser compatibile sul visore.':'AR non disponibile: occorrono HTTPS e un dispositivo con WebXR AR.');return;}try{let session=await navigator.xr.requestSession(mode,{optionalFeatures:['local-floor']});this.renderer.xr.setReferenceSpaceType('local-floor');this.ar=mode==='immersive-ar';if(this.ar){this.scene.background=null;this.world.scale.setScalar(.06);this.world.position.set(0,-.4,-1.2);}else this.rig.position.set(0,0,this.project.depth/2-1);this.camera.position.set(0,0,0);await this.renderer.xr.setSession(session);}catch(e){this.notify('Impossibile avviare la sessione immersiva: '+e.message);}}
 screenshot(){this.renderer.render(this.scene,this.camera);return this.renderer.domElement.toDataURL('image/png');}
}


