import './templates.css';
const templates=[
 {id:'atlante-materia',name:'Atlante della materia',shape:'PIANTA A L',area:488,count:52,description:'Una lunga galleria scultorea incontra un’ala raccolta. Intonaco terracotta, parquet caldo e sculture in bronzo scandiscono il percorso.',tags:'32 × 24 m · 10 fari · Altezza 4,5 m',points:'0,0 160,0 160,50 60,50 60,120 0,120'},
 {id:'corte-luce',name:'Corte della luce',shape:'TRE ALI A U',area:720,count:73,description:'Due ali espositive e una galleria di collegamento si affacciano su un vuoto centrale. Marmo chiaro, pareti blu petrolio e accenti metallici accompagnano la visita.',tags:'36 × 28 m · 13 fari · Altezza 4,5 m',points:'0,0 180,0 180,140 130,140 130,50 50,50 50,140 0,140'},
 {id:'colore-luci',name:'Abitare il colore',shape:'GALLERIA COMPATTA',area:288,count:50,description:'La mostra di partenza, con quinte bifacciali, un’isola scultorea e tre nuclei dedicati a terra, soglia e luce.',tags:'18 × 16 m · 11 fari · Altezza 4,2 m',points:'0,0 90,0 90,80 0,80'}
];
document.title='Spazio — Template di mostre';
document.querySelector('#app').innerHTML=`<div class="template-page"><header><a class="template-brand" href="/">⌑ spazio</a><nav><a href="/studio?start=resume">Torna allo studio</a><a href="/account">I miei progetti ↗</a></nav></header><main><div class="template-intro"><span class="template-eyebrow">SPAZI DA REINTERPRETARE / 01—03</span><h1>Una mostra pronta.<br/><em>Una nuova possibilità.</em></h1><p>Parti da un allestimento curato, poi fallo tuo. Cambia opere, materiali, luci e percorsi: ogni template si apre come una nuova copia modificabile.</p></div><section class="template-grid" aria-label="Mostre già allestite">${templates.map((t,i)=>`<article class="template-card" data-template="${t.id}"><a class="template-photo" href="/studio?template=${t.id}" aria-label="Crea una mostra da ${t.name}"><img src="/templates/${t.id}.webp" alt="Vista 3D dell’allestimento ${t.name}" ${i?'loading="lazy"':''}/><span class="template-number">0${i+1}</span><span class="template-area">${t.area} m²</span><span class="template-image-label">DENTRO LA MOSTRA <span>↗</span></span></a><div class="template-content"><span class="template-eyebrow">${t.shape}</span><h2>${t.name}</h2><p>${t.description}</p><div class="template-meta"><svg viewBox="-5 -5 190 150" aria-label="Schema della pianta"><polygon points="${t.points}"/></svg><div><strong>${t.count} elementi già posizionati</strong><small>${t.tags}</small></div></div><a class="template-use" href="/studio?template=${t.id}">Usa questo template <span>↗</span></a></div></article>`).join('')}</section><section class="template-recent" hidden><h2>Le tue versioni locali</h2><p>Riprendi le copie che hai già iniziato in questo browser.</p><div id="template-drafts"></div></section><aside class="template-note"><strong>Una base completa, tutta da modificare.</strong><p>Opere e immagini sono esempi di studio, riutilizzati dalla collezione dimostrativa. I perimetri a L e a U sono predefiniti; puoi modificare pareti interne e allestimento. Le copie si salvano su questo browser: esporta il file progetto per conservarle o trasferirle.</p></aside></main><footer>SPAZIO / Studio espositivo <a href="/studio?start=new">Oppure inizia da uno spazio vuoto →</a></footer></div>`;
const request=indexedDB.open('spazio-studio',1);
request.onupgradeneeded=()=>request.result.createObjectStore('projects');
request.onsuccess=()=>{const db=request.result;const cursor=db.transaction('projects').objectStore('projects').openCursor();cursor.onsuccess=()=>{const row=cursor.result;if(!row){db.close();return;}const p=row.value;if(String(row.key).startsWith('template:')&&templates.some(t=>t.id===p.templateSource)){const link=document.createElement('a');link.href='/studio?template='+p.templateSource+'&draft='+encodeURIComponent(String(row.key).slice(9));link.textContent=p.name+' →';document.querySelector('#template-drafts').append(link);document.querySelector('.template-recent').hidden=false;}row.continue();};};
